### ISSUE TITLE
Permissions issue downloading whisper 

### ISSUE THREAD

**Issue by zachequi** [busser/whisper#27]
Love this idea, thanks for creating this package.  Was googling for "Berglas for AWS" and hoping to find exactly this package.

Using the example Dockerfile:

```Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM alpine
 ---> c059bfaa849c
Step 2/3 : COPY --from=ghcr.io/busser/whisper:latest /whisper /bin/whisper
invalid from flag value ghcr.io/busser/whisper:latest: Head "https://ghcr.io/v2/busser/whisper/manifests/latest": unauthorized
```

**Comment by busser** [comment]
Hi @zachequi, thanks for reporting the issue!

The package is now public, so you should be able to pull the image.

Let me know if it works OK :)

**Comment by zachequi** [comment]
Thanks a ton for the quick response!  I can confirm it works correctly now.
