### ISSUE TITLE
Feature Request: Summary output to console

### ISSUE THREAD

**Issue by zachequi** [busser/whisper#29]
It would be handy to have a flag for whisper that causes it to produce a summary of what secrets it loaded successfully/unsuccessfully to the console

**Comment by busser** [comment]
Currently, whisper logs any errors that occur and exits if it failed to fetch a secret.

I agree that it would be nice for whisper to at least log the name of each environment variable it overloads. I'll start working on it :)

**Comment by busser** [comment]
This feature is now live on the main branch. I will close this issue after the next release.

**Comment by busser** [comment]
Whisper now does this with [release v0.4.0](https://github.com/busser/whisper/releases/tag/v0.4.0).
