### ISSUE TITLE
Feature Request: Caching Secrets

### ISSUE THREAD

**Issue by zachequi** [busser/whisper#30]
If a developer specifies the same secret across multiple envvars, and perhaps applies different filters to those variables, whisper should ideally not query the root secret store multiples times.  e.g.

```
SECRET1=awssm:12345|somefilter1
SECRET2=awssm:12345|somefilter2
SECRET3=awssm:12345|somefilter3
```

Ideally this would generate one query to AWS SM for `12345` and then apply the three different filters to generate the three different output variables.

**Comment by busser** [comment]
The caching rule is fairly straightforward: variables with identical references have identical values.

I am currently refactoring whisper's internals to support filters. I will add caching on the fly. I'll keep this issue updated as I make progress.

**Comment by busser** [comment]
Whisper now does this with [release v0.4.0](https://github.com/busser/whisper/releases/tag/v0.4.0).
